minio:
  enable: true
  business-key: avatar
  endpoint: http://localhost:9000
  access-key: minio
  secret-key: "!QAZ2wsx"
  bucket-name: avatars
  file-size-limit: 10485760 # 10MB
  expire-time: 3600 # 1小时
