server:
  port: 8081

spring:
  application:
    name: pet-care-ai

# 定时任务配置
scheduler:
  selective-vectorization:
    enabled: false
    cron: 0 0 2 * * ?

  # AI 配置
  ai:
    # 大模型
    dashscope:
      api-key: ${API_KEY}
      embedding:
        options:
          model: text-embedding-v3
    # 会话记忆
    chat:
      memory:
        redis:
          timeout: 5000
          max-messages: 10

# Aliyun OSS 配置
aliyun:
  oss:
    endpoint: ${OSS_ENDPOINT}
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: ${OSS_BUCKET_NAME}
    enabled: true

# Core 服务地址
core:
  service:
    url: ${CORE_SERVICE_URL:http://localhost:8080}

# JWT配置
jwt:
  enabled: true
  secret-key: ${JWT_SECRET_KEY}
  expire-time: 86400
  refresh-expire-time: 604800

# Web MVC 拦截器配置
web:
  mvc:
    jwt-include-paths:
      - /ai/document/**

# Actuator 配置
#management:
#  server:
#    port: ${server.port}
#  endpoints:
#    web:
#      exposure:
#        include: health,metrics,prometheus
#  endpoint:
#    prometheus:
#      enabled: true
#    health:
#      show-details: always
#  prometheus:
#    metrics:
#      export:
#        enabled: true
#  metrics:
#    tags:
#      application: ${spring.application.name}
#    enable:
#      tomcat: true
#      jvm: true
#      hikaricp: true
#      executor: true

# Knife4j 配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  production: false

# SpringDoc OpenAPI 配置
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    filter: true
  packages-to-scan: pvt.mktech.petcare.ai.controller
  cache:
    disabled: true

# 日志配置
logging:
  level:
    pvt.mktech.petcare.ai: INFO
    com.alibaba.nacos: WARN
    org.springframework.ai: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
