server:
  port: 18082

spring:
  application:
    name: pet-management-service
  datasource:
    url: jdbc:mysql://localhost:3307/pet_care?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#      config:
#        server-addr: localhost:8848
#        file-extension: yaml

# MyBatis-Flex 配置
mybatis-flex:
  configuration:
    map-underscore-to-camel-case: true
    # 日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
# SpringDoc OpenAPI 配置
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#    enabled: true
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true
#    operations-sorter: method
#    tags-sorter: alpha
#    display-request-duration: true
#    filter: true
#  packages-to-scan: pvt.mktech.petcare.controller
#  paths-to-match: /api/**
#  cache:
#    disabled: true

# 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    com.petcare.user: ${LOG_LEVEL:INFO}
    com.mybatisflex: ${SQL_LOG_LEVEL:DEBUG}
#    org.apache.rocketmq: INFO
    org.springframework: INFO
  file:
    name: logs/pet-management-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"